config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :attachments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'carrierwave/orm/activerecord'
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :report

  mount_uploaders :attachments, AttachmentUploader
  serialize :avatars, JSON # If you use SQLite, add this line.

end

app/models/report.rb
class Report < ApplicationRecord
  has_many :attachments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  def new
    @attachment = Attachment.new
  end

  def destory

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attachment_params
      params.fetch(:attachment, {}).permit(:file_name, :attachment, :report_id)
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.fetch(:report, {}).permit(:requestor, :requestor_telephone,:business_contact,:business_contact_telephone,:date_requestor_target,:title, :description,:date_from,:date_to,:output,:output_location,:output_location_notes,:format,:frequency,:is_research)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MEE Report Portal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to 'New Request', new_report_path, class: "btn btn-info" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Request Summary", reports_path, class: "nav-link" %>
      </li>

      <!--
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeeReportRequest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3> Contact </h3>
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Requestor E-mail:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_field :requestor, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Requestor Telephone</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_field :requestor_telephone, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Business Contact Name</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_field :business_contact, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Business Contact Telephone</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_field :business_contact_telephone, class: "form-control" %>
      </div>
    </div>

    <h3>Basic Information</h3>
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Date Needed:<br><em>Subject to approval</em></label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.date_field :date_requestor_target, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Report Title: <br><em>Brief Description</em></label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Description / Purpose:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </div>


    <div class="form-row">
      <div class="col-sm-5 col-md-5 col-lg-3">
        <label for="validationDefault01">Date From:</label>
        <%= form.date_field :date_from, class: "form-control" %>
      </div>
      <div class="col-sm-5 col-md-5 col-lg-3">
        <label for="validationDefault02">Date To:</label>
        <%= form.date_field :date_to, class: "form-control" %>
      </div>
    </div>
    <hr>
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Output Type:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.select(:output, [
        ["Data Extract","Data Extract"],
        ["Epic Report","Epic Report"],
        ["Tableau Report","Tableau Report"]],
        {include_blank:true}, class: "form-control")%>
      </div>
    </div>
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Output Location:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.select(:output_location, [
        ["Email","Email"],
        ["FTP","FTP"],
        ["Network Folder","Network Folder"]],
        {include_blank:true}, class: "form-control") %>
        <%= form.text_area :output_location_notes, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Format:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.select(:format, [
        ["Excel","Excel"],
        ["PDF","PDF"],
        ["Tableau","Tableau"],
        [".csv",".csv"],
        [".txt","txt"]],
        {include_blank:true}, class: "form-control") %>
      </div>
    </div>

    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Frequency:</label>
      <div class="col-sm-10 col-md-10 col-lg-5">
        <%= form.select(:frequency, [
        ["One Time (set dates)","One Time (set dates)"],
        ["On Demand","On Demand"],
        ["Daily","Daily"],
        ["Weekly","Weekly"],
        ["Monthly","Monthly"],
        ["Quarterly","Quarterly"],
        ["Yearly","Yearly"]],
        {include_blank:true}, class: "form-control") %>
      </div>
    </div>

  <h2>Research Requests</h2>
  For research related requests, please complete the following:
  <br><br>

<div class="form-group form-check">
  <input type="checkbox" name="report[is_research]" id="is_research" value="true"  class="form-check-input">
  <label for="is_research"><span>Tag as Research Request</span></label>
</div>
<br><br>

    output_fields
    sort_fields
    groupings
    metrics
    filter_criteria
    parameter_prompts
    access

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Report Request Summary</h1>

[Open/On-Hold] [Completed] [Cancelled] [All]

<br><br><br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Submitted</th>
      <th scope="col">Requestor</th>
      <th scope="col">Request</th>
      <th scope="col">Status</th>
      <th scope="col">Assigned</th>
      <th scope="col">Actions</th>

    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
    <tr>
      <td scope="row"><%= report.created_at.strftime("%m/%d/%Y") %></td>
      <td scope="row">
        <%= report.requestor %><br>
        <%= report.requestor_telephone %>
      </td>
      <td><% if report.is_research == true %><button type="button" class="btn btn-warning btn-sm">Research</button> <% end %><%= link_to report.title, report %><br>

          <%= report.description %></td>
      <td>Not Started</td>
      <td>MEE: Fran</td>

      <td><%= link_to 'Edit', edit_report_path(report) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reports/new.html.erb
<br>
<h2>Report Request Form</h2>
<br>
Click here to read our report request guidelines!<br>
Fields denoted with an "*" are required to submit the form.

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>